// <auto-generated />
namespace KnowledgeTesting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AnswerQuestion_MToM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnswerQuestion_MToM));
        
        string IMigrationMetadata.Id
        {
            get { return "202007201459338_AnswerQuestion_MToM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
